import streamlit as st
import pandas as pd
from utils.data_loader import load_portfolio, portfolio_summary
from utils.analyzer import run_analysis

# LeanIX GenAI Portfolio Analyzer
# This Streamlit app allows users to upload their LeanIX application portfolio data in CSV format, analyzes it using the Anthropic API (Claude), and generates rationalization recommendations for retirement, modernization, and risk mitigation based on the portfolio characteristics. 
# The app provides a dashboard with key metrics and visualizations, as well as a detailed AI-generated report with actionable insights for enterprise architects and CTOs.
st.set_page_config(
    page_title="LeanIX GenAI Portfolio Analyzer",
    page_icon="🏗️",
    layout="wide"
)
# The app is structured into three main tabs: Upload, Dashboard, and AI Report.
# The Upload tab allows users to upload their portfolio CSV file and triggers the analysis process.
# The Dashboard tab provides an overview of the portfolio with key metrics and visualizations.
# The AI Report tab displays the detailed recommendations generated by the Anthropic API based on the uploaded
st.title("LeanIX GenAI Portfolio Analyzer")
st.caption("Powered by Claude · Upload your portfolio CSV to begin")


# --- Session state ---
if "df" not in st.session_state:
    st.session_state.df = None
if "summary" not in st.session_state:
    st.session_state.summary = None
if "analysis" not in st.session_state:
    st.session_state.analysis = None

# --- Tabs ---
tab1, tab2, tab3 = st.tabs(["Upload", "Dashboard", "AI Report"])

# ── Tab 1: Upload ──────────────────────────────────────────
with tab1:
    uploaded = st.file_uploader(
        "Upload your LeanIX portfolio export",
        type=["csv"],
        help="CSV must include: app_name, business_capability, lifecycle_stage, "
             "tech_debt_score, business_value_score, annual_cost_usd, "
             "hosting_type, last_updated_year, owner_team"
    )
# When a file is uploaded, the app attempts to load and process the portfolio data using the load_portfolio function. If the data is successfully loaded, it is stored in the session state along with a summary of the portfolio characteristics. 
# The app then displays the loaded data in a table format for user review before analysis.
    if uploaded:
        df = load_portfolio(uploaded)
        if df is not None:
            st.session_state.df = df
            st.session_state.summary = portfolio_summary(df)
            st.success(f"Loaded {len(df)} applications successfully.")
            st.dataframe(df, use_container_width=True, hide_index=True)

    st.divider()
# If a portfolio has been loaded, the app displays a button to trigger the analysis using the Anthropic API. 
# When the button is clicked, the run_analysis function is called with the loaded DataFrame and its summary as arguments. 
# The resulting analysis, which includes recommendations for retirement, modernization, and risk mitigation, is stored in the session state and can be viewed in the AI Report tab once the analysis is complete.
    if st.session_state.df is not None:
        if st.button("Analyze portfolio with Claude →", type="primary"):
            result = run_analysis(
                st.session_state.df,
                st.session_state.summary
            )
            if result:
                st.session_state.analysis = result
                st.success("Analysis complete! Go to the AI Report tab.")

    else:
        st.info("No file uploaded yet. Using sample data? "
                "Find it in data/sample_portfolio.csv")

# ── Tab 2: Dashboard ───────────────────────────────────────
with tab2:
    if st.session_state.df is None:
        st.info("Upload a portfolio CSV first.")
    else:
        from utils.visualizer import (
            scatter_quadrant, lifecycle_bar,
            cost_by_hosting, capability_heatmap
        )

        df = st.session_state.df
        s  = st.session_state.summary

        # ── Metric row ──
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Total apps",        s["total_apps"])
        col2.metric("Annual spend",      f"${s['total_cost']:,}")
        col3.metric("High tech debt",    s["high_debt_count"],
                    help="Apps with tech debt score ≥ 7")
        col4.metric("Retire candidates", s["retire_candidates"],
                    help="Apps in End of Life or Phase Out stage")

        st.divider()

        # ── Scatter quadrant — full width ──
        st.plotly_chart(scatter_quadrant(df), use_container_width=True)
        st.caption(
            "Bubble size = annual cost. "
            "Hover over any app for full details."
        )

        st.divider()

        # ── Lifecycle + Cost side by side ──
        col_a, col_b = st.columns(2)
        with col_a:
            st.plotly_chart(lifecycle_bar(df), use_container_width=True)
        with col_b:
            st.plotly_chart(cost_by_hosting(df), use_container_width=True)

        st.divider()

        # ── Capability heatmap — full width ──
        st.plotly_chart(capability_heatmap(df), use_container_width=True)
        st.caption(
            "Red = high debt (≥7), Amber = medium (5–6), "
            "Green = healthy (<5). Hover for full stats."
        )

# ── Tab 3: AI Report ───────────────────────────────────────
with tab3:
    if st.session_state.analysis is None:
        st.info("Run the analysis in the Upload tab first.")
    else:
        from utils.visualizer import (
            scatter_quadrant, lifecycle_bar,
            cost_by_hosting, capability_heatmap
        )
        from utils.exporter import to_pdf, to_json

        a  = st.session_state.analysis
        df = st.session_state.df

        if not isinstance(a, dict):
            st.warning("Analysis returned unexpected format.")
            st.code(str(a))
            st.stop()

        # ── Executive summary ──
        st.subheader("Executive summary")
        st.info(a.get("executive_summary", ""))

        saving = a.get("total_potential_saving_usd", 0)
        if saving and saving > 0:
            st.metric("Total potential saving", f"${saving:,}/yr")

        st.divider()

        # ── Retire ──
        st.subheader("Retire recommendations")
        retire_list = a.get("retire", [])
        if not retire_list:
            st.caption("No retirement candidates identified.")
        for item in retire_list:
            if not isinstance(item, dict):
                continue
            with st.expander(
                f"{item.get('app_name','?')}  ·  "
                f"save ${item.get('estimated_saving_usd',0):,}/yr  ·  "
                f"urgency: {item.get('urgency','')}"
            ):
                st.write(item.get("reason", ""))

        st.divider()

        # ── Modernize ──
        st.subheader("Modernize recommendations")
        modernize_list = a.get("modernize", [])
        if not modernize_list:
            st.caption("No modernization candidates identified.")
        for item in modernize_list:
            if not isinstance(item, dict):
                continue
            with st.expander(
                f"{item.get('app_name','?')}  ·  "
                f"{item.get('priority','')} priority"
            ):
                st.write(item.get("reason", ""))
                approach = item.get("recommended_approach", "")
                if approach:
                    st.markdown(f"**Approach:** {approach}")

        st.divider()

        # ── Key risks ──
        st.subheader("Key risks")
        for risk in a.get("key_risks", []):
            if not isinstance(risk, dict):
                continue
            affected = ", ".join(risk.get("affected_apps", []))
            st.warning(
                f"**{risk.get('risk','')}**\n\n"
                f"Affected: {affected}\n\n"
                f"Mitigation: {risk.get('mitigation','')}"
            )

        st.divider()

        # ── Quick wins ──
        st.subheader("Quick wins")
        for qw in a.get("quick_wins", []):
            if isinstance(qw, str) and qw.strip():
                st.success(qw)

        # ── Capability gaps ──
        gaps = a.get("capability_gaps", [])
        if gaps:
            st.divider()
            st.subheader("Capability gaps")
            for gap in gaps:
                if isinstance(gap, str) and gap.strip():
                    st.info(gap)

        st.divider()

        # ── Export buttons ──
        st.subheader("Export report")

        figures = {
            "scatter":   scatter_quadrant(df),
            "lifecycle": lifecycle_bar(df),
            "cost":      cost_by_hosting(df),
            "heatmap":   capability_heatmap(df),
        }

        col1, col2 = st.columns(2)

        with col1:
            with st.spinner("Generating PDF..."):
                pdf_bytes = to_pdf(a, df, figures)
            st.download_button(
                label="Download PDF report",
                data=pdf_bytes,
                file_name="portfolio_rationalization_report.pdf",
                mime="application/pdf",
                use_container_width=True,
            )

        with col2:
            json_str = to_json(a, df)
            st.download_button(
                label="Download JSON export",
                data=json_str,
                file_name="portfolio_analysis.json",
                mime="application/json",
                use_container_width=True,
            )

        # ── Debug ──
        with st.expander("View raw AI response (debug)"):
            st.json(a)